spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 填写自己的数据库IP地址
    url: jdbc:mysql://ip:3306/nanshuo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400