# 应用服务 WEB
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # todo 注意这个端口号，我的是3305，默认是3306
    url: jdbc:mysql://127.0.0.1:3305/nanshuo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
  profiles:
    active: prod
# mybatis-plus
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

